/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as QuemSouRouteImport } from './routes/quem-sou'
import { Route as SolucoesRouteImport } from './routes/solucoes'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogAClickzacaoDaVidaRouteImport } from './routes/blog/a-clickzacao-da-vida'
import { Route as BlogAEngenhariaDoPrejuizoRouteImport } from './routes/blog/a-engenharia-do-prejuizo'
import { Route as BlogAReuniaoFantasmaVoceEstaPresenteOuApenasConectadoRouteImport } from './routes/blog/a-reuniao-fantasma-voce-esta-presente-ou-apenas-conectado'
import { Route as BlogComunicacaoNaoViolentaJamaisVaiSerPerfumariaRouteImport } from './routes/blog/comunicacao-nao-violenta-jamais-vai-ser-perfumaria'
import { Route as BlogEmpresasPrecisamEnxergarAlemDoCrachaRouteImport } from './routes/blog/empresas-precisam-enxergar-alem-do-cracha'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const QuemSouRoute = QuemSouRouteImport.update({
  id: '/quem-sou',
  path: '/quem-sou',
  getParentRoute: () => rootRouteImport,
} as any)
const SolucoesRoute = SolucoesRouteImport.update({
  id: '/solucoes',
  path: '/solucoes',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogAClickzacaoDaVidaRoute = BlogAClickzacaoDaVidaRouteImport.update({
  id: '/blog/a-clickzacao-da-vida',
  path: '/blog/a-clickzacao-da-vida',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogAEngenhariaDoPrejuizoRoute =
  BlogAEngenhariaDoPrejuizoRouteImport.update({
    id: '/blog/a-engenharia-do-prejuizo',
    path: '/blog/a-engenharia-do-prejuizo',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogAReuniaoFantasmaVoceEstaPresenteOuApenasConectadoRoute =
  BlogAReuniaoFantasmaVoceEstaPresenteOuApenasConectadoRouteImport.update({
    id: '/blog/a-reuniao-fantasma-voce-esta-presente-ou-apenas-conectado',
    path: '/blog/a-reuniao-fantasma-voce-esta-presente-ou-apenas-conectado',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogComunicacaoNaoViolentaJamaisVaiSerPerfumariaRoute =
  BlogComunicacaoNaoViolentaJamaisVaiSerPerfumariaRouteImport.update({
    id: '/blog/comunicacao-nao-violenta-jamais-vai-ser-perfumaria',
    path: '/blog/comunicacao-nao-violenta-jamais-vai-ser-perfumaria',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogEmpresasPrecisamEnxergarAlemDoCrachaRoute =
  BlogEmpresasPrecisamEnxergarAlemDoCrachaRouteImport.update({
    id: '/blog/empresas-precisam-enxergar-alem-do-cracha',
    path: '/blog/empresas-precisam-enxergar-alem-do-cracha',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/quem-sou': typeof QuemSouRoute
  '/solucoes': typeof SolucoesRoute
  '/blog/a-clickzacao-da-vida': typeof BlogAClickzacaoDaVidaRoute
  '/blog/a-engenharia-do-prejuizo': typeof BlogAEngenhariaDoPrejuizoRoute
  '/blog/a-reuniao-fantasma-voce-esta-presente-ou-apenas-conectado': typeof BlogAReuniaoFantasmaVoceEstaPresenteOuApenasConectadoRoute
  '/blog/comunicacao-nao-violenta-jamais-vai-ser-perfumaria': typeof BlogComunicacaoNaoViolentaJamaisVaiSerPerfumariaRoute
  '/blog/empresas-precisam-enxergar-alem-do-cracha': typeof BlogEmpresasPrecisamEnxergarAlemDoCrachaRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/quem-sou': typeof QuemSouRoute
  '/solucoes': typeof SolucoesRoute
  '/blog/a-clickzacao-da-vida': typeof BlogAClickzacaoDaVidaRoute
  '/blog/a-engenharia-do-prejuizo': typeof BlogAEngenhariaDoPrejuizoRoute
  '/blog/a-reuniao-fantasma-voce-esta-presente-ou-apenas-conectado': typeof BlogAReuniaoFantasmaVoceEstaPresenteOuApenasConectadoRoute
  '/blog/comunicacao-nao-violenta-jamais-vai-ser-perfumaria': typeof BlogComunicacaoNaoViolentaJamaisVaiSerPerfumariaRoute
  '/blog/empresas-precisam-enxergar-alem-do-cracha': typeof BlogEmpresasPrecisamEnxergarAlemDoCrachaRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/quem-sou': typeof QuemSouRoute
  '/solucoes': typeof SolucoesRoute
  '/blog/a-clickzacao-da-vida': typeof BlogAClickzacaoDaVidaRoute
  '/blog/a-engenharia-do-prejuizo': typeof BlogAEngenhariaDoPrejuizoRoute
  '/blog/a-reuniao-fantasma-voce-esta-presente-ou-apenas-conectado': typeof BlogAReuniaoFantasmaVoceEstaPresenteOuApenasConectadoRoute
  '/blog/comunicacao-nao-violenta-jamais-vai-ser-perfumaria': typeof BlogComunicacaoNaoViolentaJamaisVaiSerPerfumariaRoute
  '/blog/empresas-precisam-enxergar-alem-do-cracha': typeof BlogEmpresasPrecisamEnxergarAlemDoCrachaRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contato'
    | '/quem-sou'
    | '/solucoes'
    | '/blog/a-clickzacao-da-vida'
    | '/blog/a-engenharia-do-prejuizo'
    | '/blog/a-reuniao-fantasma-voce-esta-presente-ou-apenas-conectado'
    | '/blog/comunicacao-nao-violenta-jamais-vai-ser-perfumaria'
    | '/blog/empresas-precisam-enxergar-alem-do-cracha'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contato'
    | '/quem-sou'
    | '/solucoes'
    | '/blog/a-clickzacao-da-vida'
    | '/blog/a-engenharia-do-prejuizo'
    | '/blog/a-reuniao-fantasma-voce-esta-presente-ou-apenas-conectado'
    | '/blog/comunicacao-nao-violenta-jamais-vai-ser-perfumaria'
    | '/blog/empresas-precisam-enxergar-alem-do-cracha'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/contato'
    | '/quem-sou'
    | '/solucoes'
    | '/blog/a-clickzacao-da-vida'
    | '/blog/a-engenharia-do-prejuizo'
    | '/blog/a-reuniao-fantasma-voce-esta-presente-ou-apenas-conectado'
    | '/blog/comunicacao-nao-violenta-jamais-vai-ser-perfumaria'
    | '/blog/empresas-precisam-enxergar-alem-do-cracha'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContatoRoute: typeof ContatoRoute
  QuemSouRoute: typeof QuemSouRoute
  SolucoesRoute: typeof SolucoesRoute
  BlogAClickzacaoDaVidaRoute: typeof BlogAClickzacaoDaVidaRoute
  BlogAEngenhariaDoPrejuizoRoute: typeof BlogAEngenhariaDoPrejuizoRoute
  BlogAReuniaoFantasmaVoceEstaPresenteOuApenasConectadoRoute: typeof BlogAReuniaoFantasmaVoceEstaPresenteOuApenasConectadoRoute
  BlogComunicacaoNaoViolentaJamaisVaiSerPerfumariaRoute: typeof BlogComunicacaoNaoViolentaJamaisVaiSerPerfumariaRoute
  BlogEmpresasPrecisamEnxergarAlemDoCrachaRoute: typeof BlogEmpresasPrecisamEnxergarAlemDoCrachaRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quem-sou': {
      id: '/quem-sou'
      path: '/quem-sou'
      fullPath: '/quem-sou'
      preLoaderRoute: typeof QuemSouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solucoes': {
      id: '/solucoes'
      path: '/solucoes'
      fullPath: '/solucoes'
      preLoaderRoute: typeof SolucoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/a-clickzacao-da-vida': {
      id: '/blog/a-clickzacao-da-vida'
      path: '/blog/a-clickzacao-da-vida'
      fullPath: '/blog/a-clickzacao-da-vida'
      preLoaderRoute: typeof BlogAClickzacaoDaVidaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/a-engenharia-do-prejuizo': {
      id: '/blog/a-engenharia-do-prejuizo'
      path: '/blog/a-engenharia-do-prejuizo'
      fullPath: '/blog/a-engenharia-do-prejuizo'
      preLoaderRoute: typeof BlogAEngenhariaDoPrejuizoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/a-reuniao-fantasma-voce-esta-presente-ou-apenas-conectado': {
      id: '/blog/a-reuniao-fantasma-voce-esta-presente-ou-apenas-conectado'
      path: '/blog/a-reuniao-fantasma-voce-esta-presente-ou-apenas-conectado'
      fullPath: '/blog/a-reuniao-fantasma-voce-esta-presente-ou-apenas-conectado'
      preLoaderRoute: typeof BlogAReuniaoFantasmaVoceEstaPresenteOuApenasConectadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/comunicacao-nao-violenta-jamais-vai-ser-perfumaria': {
      id: '/blog/comunicacao-nao-violenta-jamais-vai-ser-perfumaria'
      path: '/blog/comunicacao-nao-violenta-jamais-vai-ser-perfumaria'
      fullPath: '/blog/comunicacao-nao-violenta-jamais-vai-ser-perfumaria'
      preLoaderRoute: typeof BlogComunicacaoNaoViolentaJamaisVaiSerPerfumariaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/empresas-precisam-enxergar-alem-do-cracha': {
      id: '/blog/empresas-precisam-enxergar-alem-do-cracha'
      path: '/blog/empresas-precisam-enxergar-alem-do-cracha'
      fullPath: '/blog/empresas-precisam-enxergar-alem-do-cracha'
      preLoaderRoute: typeof BlogEmpresasPrecisamEnxergarAlemDoCrachaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContatoRoute: ContatoRoute,
  QuemSouRoute: QuemSouRoute,
  SolucoesRoute: SolucoesRoute,
  BlogAClickzacaoDaVidaRoute: BlogAClickzacaoDaVidaRoute,
  BlogAEngenhariaDoPrejuizoRoute: BlogAEngenhariaDoPrejuizoRoute,
  BlogAReuniaoFantasmaVoceEstaPresenteOuApenasConectadoRoute:
    BlogAReuniaoFantasmaVoceEstaPresenteOuApenasConectadoRoute,
  BlogComunicacaoNaoViolentaJamaisVaiSerPerfumariaRoute:
    BlogComunicacaoNaoViolentaJamaisVaiSerPerfumariaRoute,
  BlogEmpresasPrecisamEnxergarAlemDoCrachaRoute:
    BlogEmpresasPrecisamEnxergarAlemDoCrachaRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
