/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as QuemSouRouteImport } from './routes/quem-sou'
import { Route as SolucoesRouteImport } from './routes/solucoes'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const QuemSouRoute = QuemSouRouteImport.update({
  id: '/quem-sou',
  path: '/quem-sou',
  getParentRoute: () => rootRouteImport,
} as any)
const SolucoesRoute = SolucoesRouteImport.update({
  id: '/solucoes',
  path: '/solucoes',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/quem-sou': typeof QuemSouRoute
  '/solucoes': typeof SolucoesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/quem-sou': typeof QuemSouRoute
  '/solucoes': typeof SolucoesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/quem-sou': typeof QuemSouRoute
  '/solucoes': typeof SolucoesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/contato' | '/quem-sou' | '/solucoes'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/contato' | '/quem-sou' | '/solucoes'
  id: '__root__' | '/' | '/contato' | '/quem-sou' | '/solucoes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContatoRoute: typeof ContatoRoute
  QuemSouRoute: typeof QuemSouRoute
  SolucoesRoute: typeof SolucoesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quem-sou': {
      id: '/quem-sou'
      path: '/quem-sou'
      fullPath: '/quem-sou'
      preLoaderRoute: typeof QuemSouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solucoes': {
      id: '/solucoes'
      path: '/solucoes'
      fullPath: '/solucoes'
      preLoaderRoute: typeof SolucoesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContatoRoute: ContatoRoute,
  QuemSouRoute: QuemSouRoute,
  SolucoesRoute: SolucoesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
